apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: global-api

  template:
    metadata:
      labels:
        app: global-api

    spec:

      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: global-api
          image: ghcr.io/bachelorprojectsw/global-api:078e599f1f2db36692559a620997be2b0341d5c5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8020
              hostPort: 8020
              protocol: TCP