project: default
source:
  repoURL: https://github.com/BachelorProjectSW/kubernetes_application
  path: src/cluster_api/manifest
  targetRevision: random # git branch
  directory: 
    jsonnet: {}
    include: '{*.yml,*.yaml}'
destination:
  server: https://kubernetes.default.svc #Deploy to the Kubernetes cluster Argo CD is running in
  namespace: default
syncPolicy:
  automated: 
    prune: true #Sync with git exactly
    selfHeal: true #Git is the single source of truth
    enabled: true #Sync automated
