[pytest]
addopts = --import-mode=importlib
pythonpath = .
testpaths = test
python_files = test_*.py
markers =
    unit: Unit tests
    integration: Integration tests  
    slow: Slow running tests #over 5 seconds
pythonpath = src

