[pytest]
addopts = --import-mode=importlib
pythonpath = .
testpaths = test
python_files = test_*.py
markers =
    unit: Unit tests
    integration: Integration tests  
    local: Local tests #Test that i not expected to pass github runner.

