apiVersion: apps/v1
kind: Deployment
metadata:
  name: {meta_name}
  labels:
    app: nginx
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8010
          name: web