apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: llama-server
  labels:
    app: llama-server
spec:
  selector: #manages pods with the given label
    matchLabels:
      name: llama-server
  template: #template for all pods
    metadata:
      labels:
        name: llama-server
    spec:
      initContainers: #runs before "normal" containers
        - name: download-model
          image: alpine
          command: ["sh", "-lc", "sh /scripts/init-download.sh"] #run the .sh script for downloading a model
          envFrom:
            - configMapRef:
                name: llama-settings
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
            - name: model-storage
              mountPath: /models

      containers:
        - name: llama
          image: ghcr.io/ggml-org/llama.cpp:server # official llama server image
          env:
            - name: LLAMA_ARG_MODEL
              value: /models/model.gguf
            - name: LLAMA_ARG_CTX_SIZE
              valueFrom:
                configMapKeyRef:
                  name: llama-settings
                  key: CTX_SIZE
            - name: LLAMA_ARG_HOST
              value: "0.0.0.0"
            - name: LLAMA_ARG_PORT
              value: "8080"
          volumeMounts: #/models inside the container maps to ../llama-models on the node disk.
            - name: model-storage
              mountPath: /models

      volumes: #these are the shared folders the containers can use (scripts + model files)
        - name: init-scripts
          configMap:
            name: llama-init
        - name: model-storage
          hostPath:
            path: /var/lib/llama-models
            type: DirectoryOrCreate