apiVersion: v1 #Defines the given LLM (where to download it from, and some args)
kind: ConfigMap
metadata:
  name: llama-settings
data:
  MODEL_URL: "https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF/resolve/main/Qwen3.5-35B-A3B-UD-IQ1_M.gguf" #Random model (for testing)
  MODEL_FILE: "Qwen3.5-35B-A3B-UD-IQ1_M.gguf"
  CTX_SIZE: "2048"