server {
    listen 80;
    server_name _; #Normally a website name fx. onesite.com, but we use ip so its a catch all
    location / {
        root /usr/share/nginx/html;
        #so basically:
        #Find the file
        #if nothing, just serve index
        try_files $uri /index.html; 
    }
}