apiVersion: v1
kind: Service
metadata:
  name: llama-service
spec:
  type: NodePort
  externalTrafficPolicy: Local #Only to endpoints on that node
  selector:
    app: llama-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 #Expose this Service on port 30080 on every node, traffic is forwarded to port 8080 on selected Pods