apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-api

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: cluster-api

  template:
    metadata:
      labels:
        app: cluster-api

    spec:
      serviceAccountName: cluster-api-sa

      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: cluster-api
          image: ghcr.io/bachelorprojectsw/cluster-api:cf8387c3af43098ad1cf939628781aa141a8ba15

          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8040
              hostPort: 8040
              protocol: TCP