apiVersion: v1
kind: Service
metadata:
  name: llama-service
  annotations:
     tailscale.com/proxy-class: rpi-proxy
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    name: llama-server
  ports:
    - port: 8080
      targetPort: 8080
