#Tailscale permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-secret-role
  namespace: default
rules:
  - apiGroups: [""] #Permission to create a secret, where it can store its state
    resources: ["secrets"]
    verbs: ["create"]

  - apiGroups: [""] #Permission to retrieve íts state, which can consist of keys
    resources: ["secrets"]
    resourceNames: ["tailscale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-secret-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cluster-api-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale-secret-role