name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      ELECTRICITY_MAPS_API_KEY: ${{ secrets.ELECTRICITY_MAPS_API_KEY }}
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-lgpio

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Ruff Linter
        run: |
          ruff check .

      - name: Install k3d and kubectl
        run: |
          python -m test.k3d.setup_kubernetes 

      - name: Setup postgres
        run: |
          python -m test.k3d.start_db

      - name: Create clusters and global scheduler
        run: |
          python -m test.k3d.create_clusters

      - name: Deploy manifests
        run: |
          python -m test.k3d.deploy

      - name: Run servers and port-forward
        run: |
          python -m test.k3d.run_servers &
          sleep 10
          python -m pytest
