name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Ruff Linter
        run: |
          ruff check .

      - name: Install k3d and kubectl
        run: |
          bash test/k3d/setup_kubernetes.sh 

      - name: Create cluster
        run: |
          sudo bash test/k3d/create_cluster.sh

      - name: Deploy manifests
        run: |
          bash test/k3d/deploy.sh

      - name: test
        run: |
          pytest
        env:
          KUBECONFIG: src/cluster_api/auth/k3d-devcluster.yaml
