name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Ruff Linter
        run: |
          ruff check .

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Create cluster
        run: |
          bash test/k3d/create-cluster.sh

      - name: Deploy manifests
        run: |
          bash test/k3d/deploy.sh

      - name: get authentication from the deployment
        run: |
          sudo cp /etc/rancher/k3s/k3s.yaml src/cluster_api/auth
          sudo chmod 644 src/cluster_api/auth/k3s.yaml

      - name: Install Docker
        run: |
          sudo apt install docker.io -y
          sudo systemctl start docker

      - name: Build kubernetes api server
        run: |
          docker build -t kube-api-server .

      - name: Run api server
        run: |
          docker run kube-api-server:latest

